export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  NOT_FOUND: 'NOT_FOUND',
  CELL_NOT_FOUND: 'CELL_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DUPLICATE_ACTIVITY: 'DUPLICATE_ACTIVITY',
  INVALID_FILE: 'INVALID_FILE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
